# Server
server.port=8080

# Database — PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/ParkingManagementSystem
spring.datasource.username=postgres
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# JPA — ddl-auto=none vì DB đã có sẵn từ SQL script (Database_PostgreLatest.sql)
# KHÔNG dùng "update" vì có thể tự động thay đổi schema ngoài ý muốn (Đã bật tạm thời để fix lỗi DB mismatch)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# JWT
jwt.secret=${JWT_SECRET:very_secret_key_needs_to_be_long_enough_for_hs256_at_least_32_bytes_long}
jwt.expiration=86400000

# Swagger
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs

# File upload
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

file.upload-dir=uploads/vehicles

# VNPay
vnpay.tmn-code=${VNPAY_TMN_CODE:71R5HK95}
vnpay.hash-secret=${VNPAY_HASH_SECRET:KXOYQCE7ZWVMHR01RG1LW5GG9CYDF82G}
vnpay.pay-url=${VNPAY_PAY_URL:https://sandbox.vnpayment.vn/paymentv2/vpcpay.html}
vnpay.return-url=${VNPAY_RETURN_URL:http://localhost:8080/api/payments/vnpay-return}

# Mail (Cần cập nhật username/password thực tế hoặc App Password)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=smartparking.admin25.noreply@gmail.com
spring.mail.password=xuyzztiqxhllvgxh
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
# Platerecognizer ALPR API
platerecognizer.api.token=Token b6e1e3fe20c852ab659e4cbbac2e1dfb0c37142a
platerecognizer.api.url=https://api.platerecognizer.com/v1/plate-reader/

# Backend URL cho mock payment links
app.backend-url=http://localhost:8080
