# Database — Supabase (PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:5432/ParkingManagementSystem
spring.datasource.username=postgres
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.show-sql=false

# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

# VNPay
vnpay.tmn-code=${VNPAY_TMN_CODE:71R5HK95}
vnpay.hash-secret=${VNPAY_HASH_SECRET:KXOYQCE7ZWVMHR01RG1LW5GG9CYDF82G}
vnpay.pay-url=${VNPAY_PAY_URL:https://sandbox.vnpayment.vn/paymentv2/vpcpay.html}
vnpay.return-url=${VNPAY_RETURN_URL:http://localhost:8080/api/payments/vnpay-return}

# CORS — cho phép frontend từ Vercel
spring.web.cors.allowed-origins=${FRONTEND_URL:http://localhost:5173}

# Backend URL cho mock payment links
app.backend-url=${BACKEND_URL:https://swp391-parkingmanagementsystem-1.onrender.com}
# Frontend URL cho email reset password link
app.frontend-url=${FRONTEND_URL:https://smart-parking-hcm.vercel.app}
# Mail
# --- CẤU HÌNH GMAIL CŨ (Comment lại để tham khảo) ---
# spring.mail.host=smtp.gmail.com
# spring.mail.port=587
# spring.mail.username=smartparking.admin25.noreply@gmail.com
# spring.mail.password=xuyzztiqxhllvgxh

# --- CẤU HÌNH BREVO MỚI ---
spring.mail.host=smtp-relay.brevo.com
spring.mail.port=2525
spring.mail.username=b07638001@smtp-brevo.com
spring.mail.password=xsmtpsib-89451f07eeb059198cc40a155d9c3453be33798e7bcb8eeee2a69861c1b4c9c3-3nNCTqFkmEPlfwGh
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true